sudo: required

language: java

services:
        - docker

before_install:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker info
        - docker pull $ML8_LATEST_DOCKER_IMAGE
        - docker run --name ml -d -p 8000:8000 -p 8001:8001 -p 8002:8002 -p 8200:8200 $ML8_LATEST_DOCKER_IMAGE
        - sleep 10

script:
        - ./gradlew :core:mlInit -PmlHost=localhost
        - ./gradlew :core:mlInstallAdmin -PmlHost=localhost -PmlAdminPassword=admin -PmlAdminUsername=admin
        - ./gradlew :core:mlDeploy -PmlHost=localhost
        # - echo "${TRAVIS_BUILD_DIR}"
        - pwd
        # - ls -lsa
        # - echo './gradlew test -DexamplesDir="${TRAVIS_BUILD_DIR}" -PmlHost=localhost'
        - ./gradlew test -Djob/home= "${TRAVIS_BUILD_DIR}/examples" -DexamplesDir="${TRAVIS_BUILD_DIR}/examples" --debug